<?php

namespace AppBundle\Repository;

/**
 * CompanyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends BaseRepository
{
    public function billSummary($companyId = null)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c.id, c.name, c.address, sum(b.amount) as total_bills, count(b) as count_bills')
            ->leftJoin('c.bills', 'b')
            ->groupBy('c.id');

        if ($companyId) {
            $qb->where('c.id = ?1')->setParameter(1, $companyId);
            return $qb->getQuery()->getSingleResult();
        }

        return $qb->getQuery()->getResult();
    }

    public function billList($companyId = null)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('b.id, b.amount, b.created_at')
            ->join('c.bills', 'b')
            ->where('c.id = ?1')
            ->setParameter(1, $companyId);

        return $qb->getQuery()->getScalarResult();
    }
}
